name: Deploy-ManagementAnalyticDashboardWeb

on:
  push:
    branches:
      - main
      - bedc
      - prod

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: odenigbogodfrey/quick-pay:latest
  
  redeploy_aple:
    runs-on: ubuntu-latest
    name: Redeploy webhook call
    needs: [docker]
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: http://164.92.155.136:9101/hooks/quick-pay
          data: ""
  redeploy_benin:
    runs-on: ubuntu-latest
    name: Redeploy webhook call
    # needs: [docker]
    if: github.ref == 'refs/heads/bedc'
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 159.89.28.140
          username: ${{ secrets.BEDC_SSH_USERNAME }}
          password: ${{ secrets.BEDC_SSH_PASSWORD }}
          port: 22
          script: |
            sh /home/webhook/docker-services/frontend/quick-pay/deploy.sh
    # steps:
    #   - name: Deploy docker container webhook
    #     uses: joelwmale/webhook-action@master
    #     env:
    #       #WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
    #       WEBHOOK_URL: http://67.205.169.2:9101/hooks/quick-pay
    #       data: ""
  redeploy_test:
    runs-on: ubuntu-latest
    name: Redeploy webhook call
    needs: [docker]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          #WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          WEBHOOK_URL: http://188.166.99.136:9101/hooks/quick-pay
          data: ""